// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT8DL1OJ_BF7nVCKzlW9im6ebBpMmljcM',
    appId: '1:288328800713:web:53dc4365e223f10acef018',
    messagingSenderId: '288328800713',
    projectId: 'puppeton-35d03',
    authDomain: 'puppeton-35d03.firebaseapp.com',
    storageBucket: 'puppeton-35d03.appspot.com',
    measurementId: 'G-WZZCM0JXG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5P1FFL_bkbi7PFFIxE-OlOelYaaQZ74A',
    appId: '1:288328800713:android:0306af957f186dddcef018',
    messagingSenderId: '288328800713',
    projectId: 'puppeton-35d03',
    storageBucket: 'puppeton-35d03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8DheMWcuWhbqY-w9siBC7dmZ_2udAkpE',
    appId: '1:288328800713:ios:e25312e3c1e1a5a7cef018',
    messagingSenderId: '288328800713',
    projectId: 'puppeton-35d03',
    storageBucket: 'puppeton-35d03.appspot.com',
    iosBundleId: 'com.example.puppeton',
  );
}
